###
GET https://dev-api.vaccinenotifier.org/notifier/v1/version
###
GET https://dev-api.vaccinenotifier.org/notifier/v1/pharmacies?zipcode=41805
###
POST https://dev-api.vaccinenotifier.org/notifier/v1/subscribe
content-type: 'application/json'

{
   "phone":"503.896.7999",
   "pharmacies":{
      "riteAid":[
         {
          "storeId": "4332",
          "address": "51341 W. Huron River Drive, Belleville 48111"
          },
          {
            "storeId": "7824",
            "address": "4151 S Canton Center Road, Canton 48188"
          },
          {
            "storeId": "4363",
            "address": "753 South Grove Street, Ypsilanti 48198"
          },
          {
            "storeId": "4358",
            "address": "35101 Michigan Avenue East, Wayne 48184"
          }
      ]
   }
}

###
POST https://www.walmart.com/pharmacy/v2/clinical-services/time-slots/[user id?]
Content-Type: "application/json"

{"startDate":"02172021","endDate":"02232021","imzStoreNumber":{"USStoreId":776}}